---
- name: search nginx-vts
  stat:
    path: /usr/local/bin/nginx-vts-exporter
  register: nginx_vts

- name: install binary nginx-vts
  become: yes
  get_url:
    url: "{{ nginx_vts_exporter_binary_url }}"
    dest: "/usr/local/bin/"
    checksum: "{{ nginx_vts_exporter_sum }}"
    mode: 0755
  when: not nginx_vts.stat.exists
  notify: restart nginx_vts_exporter service

  

- name: configuration nginx-vts
  template:
    src: default-config.j2
    dest: "/etc/default/{{ nginx_vts_exporter_service_name }}"
  notify: restart nginx_vts_exporter service

- name: create systemd unit nginx-vts
  template:
    src: systemd-unit.j2
    dest: "/etc/systemd/system/{{ nginx_vts_exporter_service_name }}.service"
  notify:
    - reload nginx_vts_exporter unit
    - restart nginx_vts_exporter service

- meta: flush_handlers

- name: enable systemd unit nginx-vts
  systemd:
    name: "{{ nginx_vts_exporter_service_name }}"
    enabled: true
    
- name: start nginx_vts_exporter
  ansible.builtin.service:
    name: "{{ nginx_vts_exporter_service_name }}"
    state: started
