---
- name: Add nginx repository
  apt_repository: repo='ppa:nginx/stable'

- name: Install Nginx Web Server on Debian Family
  apt:
    name=nginx
    state=latest
  when:
    ansible_os_family == "Debian"
  notify:
    - restart nginx

- name: Disable default site
  become: yes
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
