---
all:
    vars:
        ansible_user: ubuntu
        ansible_ssh_private_key_file: .ssh/id_rsa
        master: "10.0.0.18" #app01
        slave: "10.0.0.8" #app02
        url_site: "89.208.229.252" #website или адрес балансировщика
        db_mysql: "10.0.0.21"
    children:
        webservers:
            hosts:
                app01:
                    ansible_host: 185.86.146.39
                app02:
                    ansible_host: 89.208.228.214
        mysql:
            hosts:
                database:
                    ansible_host: 109.120.181.129
        monitoring:
            hosts:
                monitoring:
                    ansible_host: 185.86.145.208
        load_balancer:
            hosts:
                loadbalancer:
                    ansible_host: 89.208.229.252
        backup:
            hosts:
                backup:
                    ansible_host: 5.188.142.17