---
all:
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: /home/shuvalov/.ssh/Ubuntu-Basic-1-2-15GB-DofB99tB.pem
  children:
    webservers:
      hosts:
        app01.project.domain:
          ansible_host: 5.188.142.6
        app02.project.domain:
              ansible_host: 185.241.192.50
    mysql:
      hosts:
        MySQL-t4d-1:
          ansible_host: 87.239.109.35
    monitoring:
      hosts:
        monitoring.project.domain:
          ansible_host: 89.208.85.81
    test:
      hosts:
        test:
          ansible_host: 109.120.181.30
