---
all:
    vars:
        ansible_user: ubuntu
        ansible_ssh_private_key_file: ./MySQL-t4d-ncbHpgFq.pem
    children:
        webservers:
            hosts:
                app01.project.domain:
                    ansible_host: 5.188.142.6
                app02.project.domain:
                    ansible_host: 185.241.192.50
        mysql:
            hosts:
                db01.project.domain:
                    ansible_host: 5.188.141.58
                db02.project.domain:
                    ansible_host: 87.239.109.35
        monitoring:
            hosts:
                monitoring.project.domain:
                    ansible_host: 89.208.85.81
        test:
            hosts:
                test:
                    ansible_host: 37.139.33.181
                test2:
                    ansible_host: 95.163.180.123
        load_balancer:
            hosts:
                lb.project.domain:
                    ansible_host: 146.185.243.121