---
- name: Install MySQL
  apt:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - python3-mysqldb
    - mysql-server-8.0

- name: Start the MySQL service
  action: service name=mysql state=started
  
- name: create user mysql
  mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_pass }}"
    priv: '*.*:ALL'
    host: '%'
    state: present
    check_implicit_admin: true
    login_unix_socket: /var/run/mysqld/mysqld.sock
    
- name: Create a new database
  mysql_db:
    name: wordpress
    state: present
    check_implicit_admin: true
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Enable remote login to mysql
  lineinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: '^bind-address'
    line: 'bind-address = 0.0.0.0'
    backup: yes
    
- name: Start the MySQL service
  action: service name=mysql state=restarted
