route:
    group_by: ['alertname']
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 5m
    receiver: 'telegram'
receivers:
    - name: 'telegram'
      telegram_configs:
      - bot_token: "5194189906:AAF6rsCetWxbwaECPICclTNqne95lUN6miE"
        api_url: "https://api.telegram.org"
        chat_id: -752672460
        parse_mode: "HTML"
inhibit_rules:
    - source_match:
        severity: 'critical'
      target_match:
        severity: 'warning'
      equal: ['alertname', 'dev', 'instance']