groups:
- name: rules
  rules:
    - alert: NODE STATUS |DOWN|
      expr: up{job="node_exporter"} == 0
      for: 0m
      labels:
        severity: critical
      annotations:
        summary: "Сервис node_exporter на сервере {{ $labels.instance }} недоступен"
        description: "Возможно сервис node_exporter упал или сервер недоступен\n VALUE = {{ $value }}\n LABELS = {{ $labels }}"
        
    - alert: процессор загружен более 80%
      expr: rate(node_cpu_seconds_total{job=~"node_exporter",mode="idle"}[1m]) * 100 < 20
      for: 0m
      labels:
        severity: critical
      annotations:
        summary: "Процессор на сервере {{ $labels.instance }} загружен более 80%"

    - alert: память загружена более 70%
      expr: node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100 < 30
      for: 0m
      labels:
        severity: critical
      annotations:
        summary: "Память на сервере {{ $labels.instance }} загружена более 70%"

    - alert: Запросы превышающие 2с
      expr: nginx_upstream_responseMsec{upstream="webservers"} > 2000
      for: 0m
      labels:
        severity: critical
      annotations:
        summary: "Обращения к сайту первышают 2с {{ $labels.instance }}"
