prometheus_dir_configuration: "/etc/prometheus"
prometheus_retention_time: "365d"
prometheus_scrape_interval: "30s"
prometheus_node_exporter: true
prometheus_node_exporter_group: "all"
prometheus_nginx_vts_group: "webservers"
prometheus_load_balancer_group: "load_balancer"
prometheus_env: "production"
prometheus_var_config:
    global:
        scrape_interval: "{{ prometheus_scrape_interval }}"
        evaluation_interval: 5s
        external_labels:
            env: '{{ prometheus_env }}'
    alerting:
        alertmanagers:
            - static_configs:
                - targets:
                    - localhost:9093
    rule_files:
        - "rules.yml"

    scrape_configs:
        - job_name: prometheus
          scrape_interval: 5m
          static_configs:
              - targets: ['{{ inventory_hostname }}:9090']
