---
- name: reload nginx_vts_exporter unit
  ansible.builtin.service:
    name: "{{ nginx_vts_exporter_service_name }}"
    state: reloaded

- name: restart nginx_vts_exporter service
  ansible.builtin.service:
    name: "{{ nginx_vts_exporter_service_name }}"
    state: restarted