name: AnsibleDeploy

on: [push]

jobs:
  build:
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible requests
      - name: set ansible config secrets
        env:
          DO_SSH_KEY: ${{ secrets.DO_SSH_KEY }}
          DB_SECRET: ${{ secrets.DB_SECRET }}
        run: |
          mkdir .ssh
          echo "$DO_SSH_KEY" > .ssh/id_key
          chmod 600 .ssh/id_key
          echo "$DB_SECRET" > roles/mysql/defaults/main.yml
      - name: run exporters playbook
        run: |
          ls
          ls -ahl .ssh/
          ansible-playbook -i inventory playbook.yml