# This is a basic workflow to help you get started with Actions

name: Push comit telegram

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: -752672460
          token: 5194189906:AAF6rsCetWxbwaECPICclTNqne95lUN6miE
          message: |
            ${{ github.actor }} created commit:
            Commit message: ${{ github.event.commits[0].message }}
        
            Repository: ${{ github.repository }}
        
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
